// Словарь подписей интерфейса. Все тексты — только отсюда.
export const DICT = {
  ru: {
    "app.title": "Jira OhMyGant",
    "lang.label": "Язык",
    "app.today": "Сегодня",
    "about.version": "Версия",
    "about.author": "Автор",
    "search.dueSoon": "Срок через {n} дн.",
    "search.dueToday": "Срок сегодня",
    "search.overdue": "Срок прошёл {n} дн. назад",

    "sum.trend": "Тренд запаса до срока",
    "sum.trendHint": "Одна линия — эпик; по умолчанию жёлтые и красные, не больше {n}. Клик по названию включает и выключает линию. ⇅ — неделя, когда перенесли срок исполнения; бледный участок — восстановленная история, пунктир — ориентировочная.",
    "sum.openCard": "Карточка эпика",
    "tr.bufferAxis": "запас, нед.",
    "tr.issuesAxis": "задач",
    "tr.buffer": "запас {v} нед.",
    "tr.restored": "восстановлено",
    "tr.restoredHint": "Бледный участок — восстановленная история: срок исполнения и состав команд на ней текущие.",
    "tr.dueMoved": "Срок исполнения перенесли на {d} (неделя {week})",
    "tr.days": "дн.",
    "tr.p85": "прогноз 85% — {d}",
    "tr.due": "срок {d}",
    "tr.crossed": "С недели {d} прогноз позже срока исполнения",
    "tr.burnup": "всего {total}, готово {done}",
    "tr.forecastTitle": "Как менялся прогноз",
    "tr.burnupTitle": "Сделано против объёма",
    "tr.legend.p85": "прогноз 85%",
    "tr.legend.band": "коридор 50–85%",
    "tr.legend.due": "срок исполнения",
    "tr.legend.total": "всего задач",
    "tr.legend.done": "готово",
    "tr.noData": "Недельных записей пока мало для графика.",
    "tr.pick": "Выберите эпики в легенде.",
    "sum.ack": "Принято",
    "sum.unack": "Вернуть",
    "sum.ackHint": "Скрыть сигнал, пока он не ухудшится сверх порога",
    "sum.unackHint": "Сигнал принят; вернуть его в «Требует внимания»",
    "sum.copy.md": "Скопировать (Markdown)",
    "sum.copy.text": "Скопировать (текст)",
    "sum.copied": "Скопировано",
    "sum.copyFailed": "Не удалось скопировать",
    "sum.badgeHint": "Новых сигналов: {n}",
    "rep.title": "Сводка Jira OhMyGant — {at}",
    "rep.critical": "[критично]",
    "rep.warning": "[внимание]",
    "st.syncOtherTab": "Идёт обновление в другой вкладке — дождёмся его и перечитаем данные",
    "auto.done": "Сводка обновлена: новых сигналов — {n}",
    "auto.doneCalm": "Сводка обновлена: новых сигналов нет",
    "auto.auth": "Автообновление: войдите в Jira в этом браузере",
    "auto.error": "Автообновление не удалось: {msg}",
    "sum.unreachable": "Данные от {at}: Jira была недоступна — проверьте VPN",
    "sig.unreachable": "Автообновление: Jira была недоступна ({at}) — проверьте VPN; данные не обновлялись сегодня",
    "set.auto": "Автообновление",
    "set.autoHint": "Один раз за рабочий день, как только Jira доступна: каждые 15 минут в заданном окне плагин проверяет, доступна ли Jira (без VPN — тихо ждёт), и обновляет данные. После обновления — уведомление с числом новых сигналов. Работает, пока открыт браузер и вы вошли в Jira.",
    "set.autoEnabled": "Обновлять автоматически",
    "set.autoFrom": "Окно: с",
    "set.autoTo": "до",
    "day.1": "Пн",
    "day.2": "Вт",
    "day.3": "Ср",
    "day.4": "Чт",
    "day.5": "Пт",
    "day.6": "Сб",
    "day.7": "Вс",
    "acc.title": "Точность прогнозов: {share}% ({hits} из {n}) попали в прогноз 85%",
    "acc.titleEmpty": "Точность прогнозов: завершённых эпиков с прогнозами пока нет",
    "acc.verdict.ok": "Около 85% — прогнозу можно верить.",
    "acc.verdict.optimistic": "Заметно ниже 85% — прогноз оптимистичен: сроки выходят позже обещанного.",
    "acc.verdict.cautious": "Заметно выше 85% — прогноз перестраховывается: сроки можно обещать смелее.",
    "acc.verdict.few": "Сравнений меньше {min} — выводы делать рано.",
    "acc.horizon": "за {h} нед.: {share}% ({hits} из {n})",
    "acc.col.finish": "Факт",
    "acc.col.before": "Прогноз за {h} нед.",
    "acc.hit": "Факт уложился в прогноз 85%",
    "acc.miss": "Факт позже прогноза 85%",
    "tab.summary": "Сводка",
    "sum.empty": "Сводка появится после первого «Обновить».",
    "sum.updated": "Обновлено: {at}",
    "sum.base": "Сравнение с: {at}",
    "sum.noBase": "Сравнивать пока не с чем — изменения появятся после следующего обновления",
    "sum.baseRestored": "по восстановленным данным",
    "sum.baseOldest": "прошлый просмотр старше 30 дней — взята самая старая запись",
    "sum.mode.seen": "С последнего просмотра",
    "sum.mode.week": "За 7 дней",
    "sum.color.red": "красных: {n}",
    "sum.color.yellow": "жёлтых: {n}",
    "sum.color.green": "зелёных: {n}",
    "sum.color.unknown": "без прогноза: {n}",
    "sum.color.nodue": "без срока: {n}",
    "sum.color.done": "готовых: {n}",
    "sum.colorHint.red": "Шанс успеть меньше 50% или срок исполнения прошёл",
    "sum.colorHint.yellow": "Шанс успеть от 50 до 85%",
    "sum.colorHint.green": "Шанс успеть 85% и выше",
    "sum.colorHint.unknown": "Прогноза нет: мало истории потока или нет команд",
    "sum.colorHint.nodue": "Нет срока исполнения — опоздание не оценить",
    "sum.colorHint.done": "Эпик завершён",
    "sum.attention": "Требует внимания",
    "sum.calm": "Всё спокойно: критичных сигналов и сигналов внимания нет.",
    "sum.more": "показать ещё {n}",
    "sum.none": "Сигналов нет.",
    "sum.openEpic": "Открыть карточку эпика",
    "sum.group.changes": "Что изменилось ({n})",
    "sum.group.near": "Близко к завершению ({n})",
    "sum.group.late": "Где опаздываем ({n})",
    "sum.group.resources": "Ресурсы ({n})",
    "sum.group.quality": "Качество данных ({n})",
    "sum.portfolio": "Портфель",
    "sum.col.epic": "Эпик",
    "sum.col.buffer": "Запас, нед.",
    "sum.col.trend": "Тренд запаса",
    "sum.col.chance": "Шанс",
    "sum.col.p85": "Прогноз 85%",
    "sum.col.due": "Срок",
    "sum.col.done": "Готово",
    "sig.epicAdded": "{epic}: добавлен в выборку",
    "sig.epicDone": "{epic}: эпик завершён",
    "sig.status": "{epic}: статус «{from}» → «{to}»",
    "sig.scopeUp": "{epic}: объём вырос с {from} до {to} задач (+{n})",
    "sig.scopeUpEst": "{epic}: сумма оценок выросла на {pct}%",
    "sig.scopeDown": "{epic}: объём сократился с {from} до {to} задач (−{n})",
    "sig.shiftLater": "{epic}: прогноз 85% сдвинулся на {days} дн. позже — {from} → {to}",
    "sig.shiftEarlier": "{epic}: прогноз 85% сдвинулся на {days} дн. раньше — {from} → {to}",
    "sig.dueChanged": "{epic}: срок исполнения изменён: {from} → {to}",
    "sig.carryNew": "{epic}: новых задач с повторным переносом: {n}",
    "sig.progress": "{epic}: закрыто задач: {n}",
    "sig.near": "{epic}: готово {pct}%, прогноз 85% — {date}",
    "sig.stuckFinish": "{epic}: готово {pct}%, но {weeks} нед. не закрыто ни одной задачи",
    "sig.overdue": "{epic}: срок исполнения {due} прошёл {days} дн. назад",
    "sig.lowChance": "{epic}: шанс успеть {chance}%, запас {buffer} нед.",
    "sig.riskChance": "{epic}: шанс успеть {chance}%, запас {buffer} нед.",
    "sig.melting": "{epic}: запас тает {weeks} нед. подряд: {from} → {to} нед.",
    "sig.stall": "{epic}: в работе, но {weeks} нед. не закрыто ни одной задачи",
    "sig.chronicCarry": "{epic}: открытых задач, прошедших {sprints}+ спринтов: {n}",
    "sig.overload": "{person}: загрузка {pct}% ({section})",
    "sig.idleNearLate": "Команда {team} загружена на {pct}%, а у {epic} в бэклоге её задач: {n}",
    "sig.spread": "Команда {team}: эпиков в работе — {epics}, поток {perWeek} задач/нед., по {perEpic} на эпик",
    "sig.bottleneck": "Команда {team} замыкает прогноз в {n} эпиках: {epics}",
    "sig.firedTasks": "{person} (уволен): открытых задач — {n}",
    "sig.unassigned": "{epic}: задач текущего спринта без исполнителя — {n}",
    "sig.noDue": "{epic}: нет срока исполнения — опоздание не оценить",
    "sig.noEstimate": "{epic}: {pct}% задач без оценки",
    "sig.shortHistory": "{epic}: истории потока {weeks} нед. — прогноза нет",
    "sig.roughHistory": "{epic}: истории потока {weeks} нед. — прогноз ориентировочный",
    "sig.noTeam": "Без команды: {n} чел. ({names}) — задайте команду в Tempo или на вкладке «Команда»",
    "sig.stale": "Данные не обновлялись {days} раб. дн.",
    "sig.apiLimited": "Последняя проверка нашла закрытые Agile или Tempo API — часть данных неполная",
    "set.summary": "Сводка",
    "set.summaryHint": "Пороги сигналов вкладки «Сводка». Пустое поле — значение по умолчанию.",
    "set.sum.chanceGreen": "Шанс успеть: зелёный от, %",
    "set.sum.chanceYellow": "Шанс успеть: жёлтый от, %",
    "set.sum.shiftDays": "Значимый сдвиг прогноза, дней",
    "set.sum.scopePct": "Изменение объёма, %",
    "set.sum.scopeAbs": "… или задач",
    "set.sum.nearWeeks": "Близко к завершению: прогноз не дальше, недель",
    "set.sum.nearDonePct": "… или готово, %",
    "set.sum.stallWeeks": "Недель без закрытий — застой",
    "set.sum.meltWeeks": "Недель снижения запаса — «запас тает»",
    "set.sum.carrySprints": "Спринтов — повторный перенос",
    "set.sum.idlePct": "Простой: загрузка команды ниже, %",
    "set.sum.spreadFlow": "Распыление: потока на эпик меньше, задач/нед.",
    "set.sum.spreadWeeks": "Распыление: окно эпиков в работе, недель",
    "set.sum.bottleneckPct": "Узкое место: замыкает прогонов, %",
    "set.sum.noEstimatePct": "Нет оценок: задач без оценки больше, %",
    "set.sum.attention": "Размер «Требует внимания»",
    "set.requestTimeout": "Таймаут запроса к Jira, с",
    "tab.search": "Поиск",
    "tab.people": "По людям",
    "tab.epicPeople": "По эпикам",
    "tab.epicStories": "Эпик — история",
    "tab.views": "Ракурсы диаграммы",
    "note.toggle": "Заметки",
    "note.none": "Заметки нет",
    "note.add": "добавить",
    "note.edit": "Изменить заметку",
    "note.history": "История ({n})",
    "note.historyTitle": "Прежние заметки {key}",
    "note.stale": "заметке {n} дн.",
    "note.staleHint": "Заметка старше {n} дн. — возможно, пора обновить",
    "note.editTitle": "Заметка к {key}",
    "note.placeholder": "Статус, риски, договорённости…",
    "note.notifyWarn": "Плагин опубликует комментарий (omg comment) в эту задачу — Jira отправит письмо её наблюдателям. Прежняя заметка останется в истории.",
    "note.empty": "Текст заметки пустой",
    "note.publishError": "Не удалось сохранить заметку к {key}: {msg}",
    "note.saved": "Заметка к {key} сохранена в Jira",
    "story.project": "Проект",
    "story.noneFound": "Ни один тип задач не совпал с «Типами историй» ({setting}), поэтому под эпиками нет историй.",
    "story.noneFoundTypes": "Типы задач в показанных эпиках: {types}. Укажите тип историй в «Настройки» → «Типы историй» так, как он называется в Jira.",
    "story.useType": "Считать историями: {name}",
    "story.typeAdded": "Тип «{name}» добавлен в «Типы историй». Такие задачи больше не считаются задачами в итогах и прогнозе.",
    "story.story": "История",
    "story.noProject": "Без проекта",
    "story.noStory": "Без истории",
    "story.projectMeta": "эпиков {e} · историй {s}",
    "story.hint": "Задач: {n}, из них из других эпиков: {f}",
    "story.foreignBadge": "+{n} из др. эпиков",
    "story.foreignHint": "Задачи истории из других эпиков или без эпика: входят в итог истории, но не в итог эпика и проекта",
    "story.missing": "Не загружены (нет прав или задача удалена): {list}",
    "story.fromEpic": "из эпика {key}",
    "story.noEpic": "без эпика",
    "story.ownSprint": "Задач у истории нет — отрезок по спринту самой истории ({sprint}), без оценки",
    "story.projectBtn": "Проект…",
    "story.projectBtnHint": "Сменить проект эпика: плагин опубликует в эпик комментарий (omg project)",
    "story.projectTitle": "Проект эпика {key}",
    "story.pickProject": "Существующий проект",
    "story.orNewProject": "или новый",
    "story.newProject": "Название нового проекта",
    "story.publish": "Сохранить в Jira",
    "story.publishing": "Публикуем комментарий в Jira…",
    "story.notifyWarn": "Плагин опубликует в эпик комментарий — Jira отправит письмо наблюдателям эпика.",
    "story.publishError": "Не удалось сменить проект эпика {key}: {msg}",
    "story.noPermission": "Нужно право «Добавлять комментарии» в проекте Jira.",
    "story.projectSaved": "Эпик {key} перенесён: {name}",
    "story.rename": "Переименовать…",
    "story.renameTitle": "Переименовать проект",
    "story.renameWarn": "Новая метка будет опубликована комментарием в каждый эпик проекта — {n} шт.; наблюдатели каждого эпика получат письмо.",
    "story.renameScope": "Эпики этого проекта, которых нет в вашей выборке (их выбрали другие менеджеры), плагин не видит и не переименует — у них проект останется со старым названием.",
    "story.renaming": "Публикуем: {i} из {n}…",
    "story.renamed": "Проект переименован: «{name}», эпиков: {n}",
    "story.renamePartial": "Переименовано {ok} из {n} эпиков; не удалось (нет права комментировать?): {list}",
    "tab.team": "Команда",
    "gantt.personClick": "Раскрыть все эпики с участием {name}, остальные свернуть",
    "gantt.epicClick": "Раскрыть всех людей с задачами эпика {name}, остальных свернуть",
    "gantt.epicFilter": "Раскрыты люди с задачами эпика: {name}",
    "gantt.personFilter": "Раскрыты эпики с участием: {name}",
    "gantt.clearPersonFilter": "снять фильтр",
    "order.handle": "Перетащите, чтобы поменять порядок эпиков. Без мыши — Alt+↑ / Alt+↓",
    "order.handleAria": "Переместить эпик {name}: Alt+↑ / Alt+↓",
    "order.manual": "Порядок: вручную",
    "order.reset": "Сбросить порядок",
    "tab.settings": "Настройки",

    "team.hint": "Люди из выгрузки (исполнители задач целевых и прочих эпиков). Свойства сохраняются локально и при повторной выгрузке сопоставляются по имени.",
    "team.name": "Сотрудник",
    "team.team": "Команда",
    "team.noTeams": "Список команд пуст — задайте его в «Настройках»",
    "team.board": "Команда (доска)",
    "team.issues": "Задач",
    "team.role": "Роль",
    "team.systems": "Информационные системы",
    "team.status": "Статус",
    "team.none": "—",
    "team.notLoaded": "нет в выгрузке",
    "team.forget": "Удалить профиль",
    "team.noSystems": "Справочник систем пуст — задайте его в «Настройках»",
    "team.empty": "Нет людей: сначала выгрузите эпики.",
    "team.saved": "Сохранено",
    "team.summaryTotal": "Сотрудников: {n}",
    "team.summaryHint": "Люди из выгрузки без уволенных и аутстафа",
    "team.noRole": "без роли",
    "role.developer": "Developer",
    "role.frontend": "Frontend dev",
    "role.backend": "Backend dev",
    "role.onec": "1C dev",
    "role.qa": "QA",
    "role.analytic": "Analytic",
    "role.teamlead": "Team Lead",
    "role.support": "Support",
    "role.pm": "Project Manager",
    "role.devops": "DevOps",
    "role.sysadm": "Sysadm",
    "pstatus.staff": "Штатный сотрудник",
    "pstatus.outstaff": "Аутстаф",
    "pstatus.fired": "Уволен",
    "set.infoSystems": "Информационные системы",
    "set.infoSystemsHint": "По одной в строке (или через запятую). Используются на вкладке «Команда».",
    "set.teams": "Команды",
    "set.teamsHint": "По одной в строке (или через запятую). Из этого списка на вкладке «Команда» выбирается команда сотрудника; по нему же люди группируются на вкладке «По людям», когда Tempo API недоступен.",

    "search.placeholder": "Название эпика или ключи: PRJ-123, PRJ-124 — можно списком",
    "search.missing": "Не найдены эпики: {list}. Проверьте ключи — возможно, это не эпики или нет доступа к проекту.",
    "search.find": "Найти",
    "search.save": "Сохранить выбор",
    "search.results": "Найденные эпики",
    "search.selected": "Выбрано эпиков: {n}",
    "search.empty": "Ничего не найдено",
    "search.hint": "Отметьте эпики и нажмите «Сохранить выбор» — задачи будут скачаны в локальную базу.",
    "search.selectAll": "Выбрать все",
    "search.clear": "Снять выбор",
    "search.stored": "Сохранённые эпики",
    "search.total": "Всего: {n}",
    "search.created": "создан",
    "search.plannedStart": "план. начало",
    "search.plannedEnd": "план. завершение",
    "search.due": "срок",
    "search.createdFull": "Дата создания эпика",
    "search.plannedStartFull": "Плановое начало работ (Planned start)",
    "search.plannedEndFull": "Плановое завершение работ (Planned end)",
    "search.dueFull": "Срок исполнения (Due date)",
    "search.col.key": "Ключ",
    "search.col.name": "Название",
    "search.col.status": "Статус",
    "search.col.project": "Проект",
    "search.col.people": "Исполнитель / Постановщик",
    "search.col.labels": "Метки",
    "search.col.express": "Экспресс оценка",
    "search.expressFull": "Оценка, внесённая в сам эпик: {sum}",
    "search.col.estimate": "Оценка",
    "search.estimateFull": "Сумма оценок задач эпика: {sum} ({n} задач; отменённые не считаются)",
    "search.col.spent": "Списано",
    "search.col.pct": "Готово",
    "search.pctFull": "Выполнено по оценкам: {done} из {total} ({n} задач из {m} готово)",
    "search.pctNone": "У задач нет оценок — доля по количеству",
    "search.info": "Вся информация по эпику",
    "search.byProject": "Задач по проектам Jira",
    "fc.loading": "Считаем прогноз…",
    "fc.outlook": "Шанс успеть к сроку исполнения: {chance}% · запас {buffer} нед.",
    "fc.title": "Прогноз срока",
    "fc.none": "Прогноз не построить: нет незавершённых задач эпика или истории потока команд",
    "fc.short": "Прогноз не строится: полных недель истории {n}, нужно минимум {min}",
    "fc.warn": "Полных недель истории {n} — прогноз ориентировочный (надёжно от {ok})",
    "fc.line": "{pct}% — {weeks} нед., до {date}",
    "fc.remaining": "Осталось задач: {n}",
    "fc.last": "Чаще всех замыкает: {team} ({pct}% прогонов)",
    "fc.caveat": "Задачи считаются такими же, как в истории; зависимости между ними не учитываются.",
    "flow.chart": "Готовые задачи по неделям",
    "flow.pickHint": "Можно выбрать несколько команд — гистограмма, период и прогноз пересчитаются только по ним.",
    "fc.basis": "Считали по командам: {teams}. Остаток делят только они. История потока — {from} — {to}, {n} нед.: период их работы над эпиком, не короче {ok} нед.",
    "flow.all": "Все команды",
    "flow.barHint": "{from} – {to}: завершено {total}, из них по эпику {epic}",
    "flow.title": "Поток команд и доля эпика",
    "flow.none": "История потока пуста — нажмите «Обновить»",
    "flow.short": "Полных недель: {n}. Для прогноза нужно минимум 5, надёжно от 12.",
    "flow.window": "Окно: {from} — {to}, полных недель: {n}",
    "flow.rowHint": "{team}: поток {median} задач/нед. (пик {max}). Доля эпика за период его активности — {pct}% ({done} из {total} завершённых за {weeks} нед.); за последние {rw} нед. — {rpct}%; за всё окно истории — {apct}% ({adone} из {atotal})",
    "people.estHint": "Время в секциях — оставшаяся оценка (Remaining estimate); если поле пустое, берётся исходная (Original estimate).",
    "flow.spanNote": "Доля — за период активности эпика: {from} — {to}, {n} нед. (суммарно {pct}%). Недели вне периода на гистограмме приглушены.",
    "flow.col": "команда · поток · доля эпика",
    "share.title": "Списания по командам (часы)",
    "share.loading": "Считаем списания по задачам эпика…",
    "share.none": "Списаний по эпику с даты его создания не найдено",
    "share.error": "Не удалось посчитать: {msg}",
    "share.noTeam": "Вне команд",
    "share.header": "команда · списано · ёмкость · доля",
    "share.formula": "Ёмкость = участники × {days} дн. × {hours} ч × {sprints} спр. (с {from})",
    "share.rowHint": "{team}: списано {spent} из ёмкости {cap} ({members} чел.) — {pct}%",
    "search.infoTitle": "Эпик {key}",
    "search.spentFull": "Списано времени: на сам эпик {epic}, на его задачи {issues} (задач со списаниями: {n} из {total})",
    "search.clearFilters": "Снять фильтры",
    "search.filters": "Фильтры:",
    "search.filterByLabel": "Показать только эпики с меткой «{v}»",
    "search.filterByAssignee": "Показать только эпики исполнителя «{v}»",
    "search.filterLabel": "метка",
    "search.filterAssignee": "исполнитель",
    "search.moreLabels": "ещё {n}",
    "search.assignee": "Исполнитель",
    "search.reporter": "Постановщик",
    "gantt.filterAssignee": "Исполнитель эпика",
    "gantt.filterAll": "— все —",
    "gantt.filterNone": "Без исполнителя",
    "gantt.fromSearch": "Со страницы «Поиск эпиков»:",
    "gantt.hiddenUnchecked": "скрыто снятыми галочками: {n}",
    "gantt.clearSearchFilters": "снять фильтры",
    "set.plannedStart": "Поле «Плановое начало»",
    "set.plannedEnd": "Поле «Плановое завершение»",
    "set.plannedHint": "Список полей типа «дата» появляется после «Определить поля Jira». Если автоопределение выбрало не то поле (в Jira бывают одноимённые), укажите нужное вручную и нажмите «Обновить данные».",
    "set.fieldAuto": "— не задано —",
    "set.epicAssignee": "Поле «Исполнитель эпика»",
    "set.epicReporter": "Поле «Постановщик эпика»",
    "set.peopleHint": "По умолчанию — стандартные Assignee и Reporter. Список полей типа «пользователь» появляется после «Определить поля Jira»; после смены нажмите «Обновить данные».",
    "set.stdAssignee": "Assignee (стандартное)",
    "set.stdReporter": "Reporter (стандартное)",
    "set.stdCreator": "Creator (стандартное)",

    "toolbar.refresh": "Обновить",
    "toolbar.reload": "Скачать",
    "toolbar.lastSync": "Обновлено: {t}",
    "toolbar.never": "ещё не загружалось",
    "toolbar.stats": "Эпиков: {e} · задач: {i} · спринтов: {s}",

    "gantt.epic": "Эпик",
    "gantt.assignee": "Исполнитель",
    "gantt.project": "Проект",
    "gantt.count": "Задач",
    "gantt.sum": "Оценка",
    "gantt.noData": "Нет данных. Выберите эпики на вкладке «Поиск эпиков».",
    "gantt.noSprints": "Не найдено ни одного текущего или будущего спринта.",
    "gantt.noAssignee": "Без исполнителя",
    "gantt.noEpic": "Без эпика",
    "gantt.targetEpic": "Эпик отмечен на вкладке «Поиск»",
    "gantt.current": "текущий",
    "gantt.future": "будущий",
    "gantt.team": "Команда",
    "gantt.noTeam": "Без команды",
    "gantt.teamFromSprints": "Доска #{id} недоступна — имя выведено из названий её спринтов",
    "gantt.noDates": "Без дат",
    "gantt.teams": "Доски:",
    "gantt.left": "Осталось задач не в статусе «Готово»",
    "gantt.others": "Прочие",
    "gantt.backlog": "Бэклог",
    "gantt.offSprint": "Вне спринта",
    "gantt.offSprintHint": "Задача не в спринте (канбан). Показана в текущей секции, потому что в работе",
    "gantt.backlogHint": "без спринта, не готово",
    "gantt.clickIssues": "Показать задачи",
    "gantt.doneShare": "Готово: {done} из {total}",
    "gantt.overload": "Перегрузка: {sum} при ёмкости спринта {cap}",
    "gantt.headerMore": "ещё {n} — показать все",
    "gantt.dueIn": "Срок {date} · через {n} дн.",
    "gantt.dueToday": "Срок {date} · сегодня",
    "gantt.dueOverdue": "Срок {date} · просрочен на {n} дн.",
    "gantt.dueDone": "Срок {date} · эпик готов",
    "gantt.plannedIn": "Плановое завершение {date} · через {n} дн.",
    "gantt.plannedToday": "Плановое завершение {date} · сегодня",
    "gantt.plannedOverdue": "Плановое завершение {date} · прошло {n} дн. назад",
    "gantt.plannedDone": "Плановое завершение {date} · эпик готов",
    "gantt.alsoPlanned": "плановое завершение {date}",
    "gantt.dueBeforeChart": "раньше текущего спринта",
    "gantt.dueAfterChart": "позже последнего спринта на графике",
    "gantt.legendDue": "срок ◆, план ◇",
    "gantt.headerLess": "свернуть список спринтов",
    "gantt.legendDone": "доля готовых задач",
    "tip.issuesCount": "Задач: {n}",
    "gantt.othersHint": "Задачи в прочих эпиках (текущий и будущие спринты)",
    "gantt.targetPart": "Целевые эпики",
    "gantt.otherPart": "Прочие эпики",
    "tip.others": "Задач в прочих эпиках",
    "tip.systems": "Информационные системы",
    "crit.button": "Критический путь: подсветить людей, определяющих срок эпика",
    "crit.on": "Критический путь включён — снять подсветку",
    "crit.defines": "определяет конец эпика: остаток {rem}, последний спринт {sprint}",
    "crit.definesNoSprint": "определяет конец эпика: самый большой остаток {rem}",
    "crit.overCapacity": "не укладывается в срок: остаток {rem} при ёмкости {cap} до {due}",
    "crit.none": "Критичных людей нет: открытых задач с оценкой не осталось",
    "cmt.button": "Прокомментировать",
    "cmt.title": "Комментарии · {key}",
    "cmt.placeholder": "Новый комментарий…",
    "cmt.save": "Сохранить",
    "cmt.saving": "Сохраняем…",
    "cmt.saved": "Сохранено",
    "cmt.loading": "Загрузка…",
    "cmt.empty": "Комментариев пока нет",
    "cmt.recent": "Последние {n}",
    "cmt.error": "Не удалось: {msg}",
    "cmt.mentionHint": "@ — упомянуть коллегу (Jira пришлёт ему уведомление)",
    "cmt.mentionSearching": "Ищем…",
    "cmt.mentionNone": "Никого не найдено",
    "cmp.button": "Кто может подменить",
    "cmp.title": "Замена для {name}",
    "cmp.noProfile": "У сотрудника не заполнены роль или информационные системы — задайте их на вкладке «Команда».",
    "cmp.criteria": "Критерии: та же роль и хотя бы одна общая информационная система; уволенные не учитываются.",
    "cmp.candidates": "Могут подменить",
    "cmp.none": "Подходящих сотрудников не найдено.",
    "cmp.common": "общих систем: {n}",
    "cmp.load": "Занятость по спринтам",
    "cmp.loadCurrent": "текущий",
    "cmp.loadHint": "{caption}: {sum} из {cap} — {pct}%",
    "cmp.loadNoCap": "{caption}: {sum} (ёмкость спринта не задана)",
    "cmp.uncovered": "Системы без замены",
    "cmp.allCovered": "все системы сотрудника покрыты",
    "tip.noSystems": "не указаны",
    "tip.otherEpics": "Прочие эпики (текущий и будущие спринты)",
    "st.othersLoading": "Загружаем задачи людей вне целевых эпиков: {n}",
    "err.others": "Не удалось загрузить задачи людей вне целевых эпиков: {msg}",
    "st.commentsLoading": "Читаем комментарии эпиков и историй: {n} из {total}",
    "st.linkedLoading": "Загружаем задачи историй из других эпиков: {n} из {total}",
    "err.comments": "Не удалось прочитать комментарии эпиков и историй (метки проектов и заметки остались прежними): {msg}",
    "err.linked": "Не удалось загрузить задачи историй из других эпиков: {msg}",
    "prio.none": "Приоритет не задан",
    "set.storyTypes": "Типы историй",
    "set.storyTypesHint": "Через запятую. Задачи этих типов в выбранных эпиках — истории для ракурса «Эпик — история». В подсчётах они не участвуют никогда, даже если их нет в «Типах задач, не учитываемых в подсчётах». Название — как его показывает Jira на вашем языке. По умолчанию — User Story, Story, История.",
    "set.storyLinkType": "Связь задачи с историей",
    "set.storyLinkTypeHint": "Название типа связи Jira, которой задачи привязаны к истории; направление не важно. По умолчанию — Relates («relates to»). Вступает в силу после «Обновить».",
    "set.noteStaleDays": "Заметка устарела через, дней",
    "set.noteStaleDaysHint": "Заметка к эпику или истории старше стольких дней помечается как устаревшая. По умолчанию — 14.",
    "gantt.expandAll": "Развернуть всё",
    "gantt.collapseAll": "Свернуть всё",

    "tip.total": "Всего задач",
    "tip.done": "Из них в статусе «Готово»",
    "tip.other": "Из них в прочих статусах",
    "tip.noSprint": "Задач без спринта",
    "tip.sum": "Суммарная оценка",
    "tip.byProject": "По проектам",
    "tip.byAssignee": "По исполнителям",
    "tip.close": "Закрыть",

    "set.connection": "Подключение",
    "set.baseUrl": "Адрес Jira",
    "set.baseUrlHint": "Например: https://jira.company.local",
    "set.pat": "Personal Access Token (запасной способ)",
    "set.patHint": "Используется, только если сессионные cookie не сработали (401/403).",
    "set.grant": "Разрешить доступ к домену",
    "set.test": "Проверить подключение",
    "set.fields": "Поля",
    "set.estimateField": "Что считать оценкой",
    "set.estimate.original": "Original Estimate (часы)",
    "set.estimate.remaining": "Remaining Estimate (часы)",
    "set.estimate.points": "Story Points",
    "set.hoursPerDay": "Часов в рабочем дне",
    "set.flowWeeks": "Окно истории потока (недель)",
    "set.flowWeeksHint": "За этот период выгружаются завершённые задачи людей — основа прогноза сроков. Прогноз требует минимум 5 полных недель, надёжен от 12.",
    "set.flowDiag": "История потока",
    "set.flowDiagEmpty": "Ещё не выгружалась — нажмите «Обновить».",
    "set.flowDiagText": "Задач с датой завершения: {n}, недель с данными: {weeks}, людей: {people}.",
    "set.flowDiagGap": "Внимание: у {n} из {total} готовых задач целевых эпиков нет даты завершения ({pct}%) — их поток не виден. Обычно так ведут себя статусы вне категории «Готово», например «On Prod».",
    "set.flowDiagOk": "Все готовые задачи целевых эпиков имеют дату завершения.",
    "set.tempo": "Брать команды из Tempo",
    "set.tempoHint": "Если в Jira установлен Tempo, состав команд берётся из него (/rest/tempo-teams/2/team). Иначе команда определяется по доске спринтов человека.",
    "set.sprintDays": "Длительность спринта (рабочих дней)",
    "set.sprintDaysHint": "Ёмкость человека на спринт: дни × часы в дне. Если оценки задач в спринте её превышают, секция на вкладке «По людям» обводится красным.",
    "set.forecastExcludeTypes": "Типы задач, не учитываемые в подсчётах",
    "set.forecastExcludeTypesHint": "Через запятую. Такие задачи не входят в число задач эпика (список «Сохранённые эпики» и карточка по «+»: по проектам, готовность, оценки, задачи со списаниями), в прогноз сроков (поток команд, доля эпика, гистограмма, остаток), в полосы и подсказки «По эпикам» и в загрузку людей (окно ⇄, перегруз в «Сводке»). «По людям» показывает все задачи человека. Списанное на них время в «Списано» остаётся. По умолчанию — User Story: история лишь объединяет задачи, которые и так посчитаны. Для прогноза вступает в силу после «Обновить». «Типы историй» исключаются всегда, даже если их здесь нет.",
    "set.doneStatuses": "Статусы, означающие «Готово»",
    "set.doneStatusesHint": "Через запятую — статусы вашего потока, которые считаются завершёнными сверх стандартных (Готово, Закрыто, On Prod). Например: Sign off, На саппорте.",
    "set.detect": "Определить поля Jira",
    "set.detected": "Epic Link: {e} · Epic Name: {en} · Sprint: {s} · Story Points: {p} · Planned start: {ps} · Planned end: {pe}",
    "set.sprints": "Спринты",
    "set.board": "Доска (rapid board)",
    "set.boardHint": "Спринты и их даты берутся с доски; если доска не выбрана — из полей самих задач.",
    "set.boardNone": "— не выбрана (брать из задач) —",
    "set.loadBoards": "Загрузить список досок",
    "set.save": "Сохранить настройки",
    "set.saved": "Настройки сохранены",
    "set.config": "Предварительная конфигурация",
    "set.configHint": "JSON с адресом Jira, полями, справочником систем, списком эпиков и сотрудниками. Перед применением локальная база очищается полностью (включая профили сотрудников), затем по шагам: поля и системы → выгрузка эпиков → роли и системы сотрудников. Файл с текущей конфигурацией можно скачать кнопкой «Экспорт».",
    "set.configApply": "Загрузить и применить",
    "set.configExport": "Экспорт конфигурации",
    "set.configLog": "Журнал",
    "cfg.badJson": "Некорректный JSON: {msg}",
    "cfg.baseUrlSet": "Адрес Jira: {url}",
    "cfg.fieldNotFound": "Поле «{name}» не найдено в Jira",
    "cfg.fieldSet": "Поле {key}: {id}",
    "cfg.systemsSet": "Информационные системы: {n}",
    "cfg.teamsSet": "Команды: {n}",
    "cfg.wiped": "Старая база очищена (эпики, задачи, спринты, профили сотрудников)",
    "cfg.epicsSaved": "Эпики: найдено и сохранено {n}",
    "cfg.orderSet": "Ручной порядок эпиков: {n}",
    "cfg.epicsMissing": "Не найдены эпики: {list}",
    "cfg.peopleSaved": "Сотрудники: обновлено профилей {n}",
    "cfg.badRole": "{name}: неизвестная роль «{role}» — пропущена",
    "cfg.badStatus": "{name}: неизвестный статус «{status}» — пропущен",
    "cfg.error": "Ошибка: {msg}",
    "cfg.start": "Применяем конфигурацию…",
    "cfg.syncing": "Выгружаем задачи эпиков…",
    "cfg.done": "Конфигурация применена",
    "set.danger": "Локальная база",
    "set.wipe": "Очистить базу",
    "set.wipeDone": "База очищена",

    "unit.h": "ч",
    "unit.d": "д",
    "unit.sp": "SP",
    "dash": "—",

    "st.connecting": "Подключение…",
    "st.ok": "Подключено: {name}",
    "st.epicsLoading": "Ищем эпики…",
    "st.issuesLoading": "Загружаем задачи: {n}",
    "st.sprintsLoading": "Загружаем спринты…",
    "st.forecasting": "Считаем прогнозы эпиков…",
    "st.backfill": "Восстанавливаем историю эпиков: {i} из {n}…",
    "st.saving": "Сохраняем данные…",
    "st.done": "Готово",
    "st.schemaUpgrade": "В задачах появились новые поля — выгружаем всё заново…",
    "st.flowLoading": "Загружаем историю завершённых задач: {n}",
    "st.flowSummary": "История потока: {issues} завершённых задач за {weeks} нед. по {logins} чел.",
    "st.apiCheck": "Проверяем доступность API…",
    "st.apiAgileLimited": "Jira Agile API недоступен ({msg}) — доски и даты будущих спринтов не подтянутся",
    "st.apiTempoLimited": "Jira Tempo API недоступен ({msg}) — команды берутся из вкладки «Команда»",
    "st.tempoLoading": "Загружаем команды Tempo…",
    "st.tempoSummary": " · команд Tempo: {teams}, участников: {members}",
    "st.sprintsSummary": "Готово · незакрытых спринтов: {n}, с датами: {dated}, без дат: {undated}{named}{failed}",
    "st.sprintsFromName": " · даты из названия: {n}",
    "st.sprintsFailed": " · не удалось перечитать: {n}",
    "st.boardsFailed": "Доска из настроек недоступна — {list}. Спринты перечитаны по одному.",
    "err.noBaseUrl": "Укажите адрес Jira в настройках",
    "err.auth": "Jira не авторизовала запрос. Войдите в Jira в этом браузере или укажите PAT в настройках.",
    "err.apiCore": "Jira API недоступен: {msg}. Выгрузка невозможна.",
    "err.apiSearch": "Поиск по JQL недоступен (/rest/api/2/search): {msg}. Выгрузка невозможна.",
    "err.http": "Ошибка Jira {code}: {msg}",
    "err.network": "Jira недоступна — проверьте VPN и сеть. Если VPN включён, проверьте адрес Jira и разрешение на домен. Данные не изменены.",
    "err.noPermission": "Нет разрешения на домен Jira. Нажмите «Разрешить доступ к домену» в настройках.",
    "err.noEpicField": "Не найдено поле «Epic Link». Нажмите «Определить поля Jira» в настройках."
  },

  en: {
    "app.title": "Jira OhMyGant",
    "lang.label": "Language",
    "app.today": "Today",
    "about.version": "Version",
    "about.author": "Author",
    "search.dueSoon": "Due in {n} days",
    "search.dueToday": "Due today",
    "search.overdue": "Overdue by {n} days",

    "sum.trend": "Buffer trend",
    "sum.trendHint": "One line per epic; yellow and red by default, at most {n}. Click a name to toggle its line. ⇅ — the week the due date moved; pale — restored history, dashed — indicative.",
    "sum.openCard": "Epic card",
    "tr.bufferAxis": "buffer, wk",
    "tr.issuesAxis": "issues",
    "tr.buffer": "buffer {v} wk",
    "tr.restored": "restored",
    "tr.restoredHint": "Pale part — restored history: the due date and teams on it are the current ones.",
    "tr.dueMoved": "Due date moved to {d} (week of {week})",
    "tr.days": "days",
    "tr.p85": "85% forecast — {d}",
    "tr.due": "due {d}",
    "tr.crossed": "From the week of {d} the forecast is later than the due date",
    "tr.burnup": "total {total}, done {done}",
    "tr.forecastTitle": "How the forecast changed",
    "tr.burnupTitle": "Done vs scope",
    "tr.legend.p85": "85% forecast",
    "tr.legend.band": "50–85% range",
    "tr.legend.due": "due date",
    "tr.legend.total": "total issues",
    "tr.legend.done": "done",
    "tr.noData": "Too few weekly records for a chart yet.",
    "tr.pick": "Pick epics in the legend.",
    "sum.ack": "Got it",
    "sum.unack": "Restore",
    "sum.ackHint": "Hide the signal until it gets worse beyond the threshold",
    "sum.unackHint": "The signal is acknowledged; bring it back to “Needs attention”",
    "sum.copy.md": "Copy (Markdown)",
    "sum.copy.text": "Copy (text)",
    "sum.copied": "Copied",
    "sum.copyFailed": "Copy failed",
    "sum.badgeHint": "New signals: {n}",
    "rep.title": "Jira OhMyGant summary — {at}",
    "rep.critical": "[critical]",
    "rep.warning": "[warning]",
    "st.syncOtherTab": "Another tab is refreshing — waiting for it, then reloading the data",
    "auto.done": "Summary updated: new signals — {n}",
    "auto.doneCalm": "Summary updated: no new signals",
    "auto.auth": "Auto refresh: log into Jira in this browser",
    "auto.error": "Auto refresh failed: {msg}",
    "sum.unreachable": "Data from {at}: Jira was unreachable — check the VPN",
    "sig.unreachable": "Auto refresh: Jira was unreachable ({at}) — check the VPN; data was not refreshed today",
    "set.auto": "Auto refresh",
    "set.autoHint": "Once per working day, as soon as Jira is reachable: every 15 minutes within the window the plugin checks whether Jira responds (without the VPN it quietly waits) and refreshes the data. Afterwards — a notification with the number of new signals. Works while the browser is open and you are logged into Jira.",
    "set.autoEnabled": "Refresh automatically",
    "set.autoFrom": "Window: from",
    "set.autoTo": "to",
    "day.1": "Mon",
    "day.2": "Tue",
    "day.3": "Wed",
    "day.4": "Thu",
    "day.5": "Fri",
    "day.6": "Sat",
    "day.7": "Sun",
    "acc.title": "Forecast accuracy: {share}% ({hits} of {n}) within the 85% forecast",
    "acc.titleEmpty": "Forecast accuracy: no finished epics with forecasts yet",
    "acc.verdict.ok": "About 85% — the forecast can be trusted.",
    "acc.verdict.optimistic": "Well below 85% — the forecast is optimistic: delivery comes later than promised.",
    "acc.verdict.cautious": "Well above 85% — the forecast is over-cautious: you can promise bolder dates.",
    "acc.verdict.few": "Fewer than {min} comparisons — too early to judge.",
    "acc.horizon": "{h} wk ahead: {share}% ({hits} of {n})",
    "acc.col.finish": "Actual",
    "acc.col.before": "Forecast {h} wk ahead",
    "acc.hit": "Delivered within the 85% forecast",
    "acc.miss": "Delivered after the 85% forecast",
    "tab.summary": "Summary",
    "sum.empty": "The summary appears after the first “Refresh”.",
    "sum.updated": "Updated: {at}",
    "sum.base": "Compared with: {at}",
    "sum.noBase": "Nothing to compare with yet — changes appear after the next refresh",
    "sum.baseRestored": "restored data",
    "sum.baseOldest": "the last view is older than 30 days — the oldest record is used",
    "sum.mode.seen": "Since last view",
    "sum.mode.week": "Last 7 days",
    "sum.color.red": "red: {n}",
    "sum.color.yellow": "yellow: {n}",
    "sum.color.green": "green: {n}",
    "sum.color.unknown": "no forecast: {n}",
    "sum.color.nodue": "no due date: {n}",
    "sum.color.done": "done: {n}",
    "sum.colorHint.red": "Chance below 50% or the due date has passed",
    "sum.colorHint.yellow": "Chance from 50 to 85%",
    "sum.colorHint.green": "Chance 85% or higher",
    "sum.colorHint.unknown": "No forecast: too little flow history or no teams",
    "sum.colorHint.nodue": "No due date — lateness cannot be judged",
    "sum.colorHint.done": "The epic is done",
    "sum.attention": "Needs attention",
    "sum.calm": "All calm: no critical or warning signals.",
    "sum.more": "show {n} more",
    "sum.none": "No signals.",
    "sum.openEpic": "Open the epic card",
    "sum.group.changes": "What changed ({n})",
    "sum.group.near": "Close to done ({n})",
    "sum.group.late": "Running late ({n})",
    "sum.group.resources": "Resources ({n})",
    "sum.group.quality": "Data quality ({n})",
    "sum.portfolio": "Portfolio",
    "sum.col.epic": "Epic",
    "sum.col.buffer": "Buffer, wk",
    "sum.col.trend": "Buffer trend",
    "sum.col.chance": "Chance",
    "sum.col.p85": "Forecast 85%",
    "sum.col.due": "Due",
    "sum.col.done": "Done",
    "sig.epicAdded": "{epic}: added to the selection",
    "sig.epicDone": "{epic}: the epic is done",
    "sig.status": "{epic}: status “{from}” → “{to}”",
    "sig.scopeUp": "{epic}: scope grew from {from} to {to} issues (+{n})",
    "sig.scopeUpEst": "{epic}: total estimate grew by {pct}%",
    "sig.scopeDown": "{epic}: scope shrank from {from} to {to} issues (−{n})",
    "sig.shiftLater": "{epic}: the 85% forecast moved {days} days later — {from} → {to}",
    "sig.shiftEarlier": "{epic}: the 85% forecast moved {days} days earlier — {from} → {to}",
    "sig.dueChanged": "{epic}: due date changed: {from} → {to}",
    "sig.carryNew": "{epic}: new repeatedly carried-over issues: {n}",
    "sig.progress": "{epic}: issues closed: {n}",
    "sig.near": "{epic}: {pct}% done, 85% forecast — {date}",
    "sig.stuckFinish": "{epic}: {pct}% done, but no issue closed for {weeks} weeks",
    "sig.overdue": "{epic}: due date {due} passed {days} days ago",
    "sig.lowChance": "{epic}: chance {chance}%, buffer {buffer} wk",
    "sig.riskChance": "{epic}: chance {chance}%, buffer {buffer} wk",
    "sig.melting": "{epic}: buffer shrinking {weeks} weeks in a row: {from} → {to} wk",
    "sig.stall": "{epic}: in progress, but no issue closed for {weeks} weeks",
    "sig.chronicCarry": "{epic}: open issues that went through {sprints}+ sprints: {n}",
    "sig.overload": "{person}: load {pct}% ({section})",
    "sig.idleNearLate": "Team {team} is loaded at {pct}%, while {epic} has {n} of its issues in the backlog",
    "sig.spread": "Team {team}: {epics} epics in progress, flow {perWeek} issues/wk, {perEpic} per epic",
    "sig.bottleneck": "Team {team} is the last to finish in {n} epics: {epics}",
    "sig.firedTasks": "{person} (left): open issues — {n}",
    "sig.unassigned": "{epic}: current-sprint issues without assignee — {n}",
    "sig.noDue": "{epic}: no due date — lateness cannot be judged",
    "sig.noEstimate": "{epic}: {pct}% of issues without an estimate",
    "sig.shortHistory": "{epic}: {weeks} weeks of flow history — no forecast",
    "sig.roughHistory": "{epic}: {weeks} weeks of flow history — the forecast is indicative",
    "sig.noTeam": "Without a team: {n} people ({names}) — set the team in Tempo or on the “Team” tab",
    "sig.stale": "Data not refreshed for {days} working days",
    "sig.apiLimited": "The last check found the Agile or Tempo API closed — some data is incomplete",
    "set.summary": "Summary",
    "set.summaryHint": "Signal thresholds for the “Summary” tab. An empty field means the default.",
    "set.sum.chanceGreen": "Chance: green from, %",
    "set.sum.chanceYellow": "Chance: yellow from, %",
    "set.sum.shiftDays": "Significant forecast shift, days",
    "set.sum.scopePct": "Scope change, %",
    "set.sum.scopeAbs": "… or issues",
    "set.sum.nearWeeks": "Close to done: forecast within, weeks",
    "set.sum.nearDonePct": "… or done, %",
    "set.sum.stallWeeks": "Weeks without closures — stall",
    "set.sum.meltWeeks": "Weeks of shrinking buffer — “buffer melting”",
    "set.sum.carrySprints": "Sprints — repeated carry-over",
    "set.sum.idlePct": "Idle: team load below, %",
    "set.sum.spreadFlow": "Spread: flow per epic below, issues/wk",
    "set.sum.spreadWeeks": "Spread: window of active epics, weeks",
    "set.sum.bottleneckPct": "Bottleneck: last-to-finish share, %",
    "set.sum.noEstimatePct": "No estimates: issues without estimate above, %",
    "set.sum.attention": "“Needs attention” size",
    "set.requestTimeout": "Jira request timeout, s",
    "tab.search": "Search",
    "tab.people": "By people",
    "tab.epicPeople": "By epics",
    "tab.epicStories": "Epic — story",
    "tab.views": "Chart views",
    "note.toggle": "Notes",
    "note.none": "No note",
    "note.add": "add",
    "note.edit": "Edit note",
    "note.history": "History ({n})",
    "note.historyTitle": "Earlier notes of {key}",
    "note.stale": "note is {n} d old",
    "note.staleHint": "The note is older than {n} days — maybe time to update it",
    "note.editTitle": "Note on {key}",
    "note.placeholder": "Status, risks, agreements…",
    "note.notifyWarn": "The plugin will post an (omg comment) comment to this issue — Jira will email its watchers. The previous note stays in the history.",
    "note.empty": "The note is empty",
    "note.publishError": "Failed to save the note on {key}: {msg}",
    "note.saved": "Note on {key} saved to Jira",
    "story.project": "Project",
    "story.noneFound": "No issue type matches “Story types” ({setting}), so there are no stories under the epics.",
    "story.noneFoundTypes": "Issue types in the shown epics: {types}. Set the story type in “Settings” → “Story types” exactly as it is named in Jira.",
    "story.useType": "Treat as stories: {name}",
    "story.typeAdded": "“{name}” added to “Story types”. Such issues are no longer counted as tasks in totals and the forecast.",
    "story.story": "Story",
    "story.noProject": "No project",
    "story.noStory": "No story",
    "story.projectMeta": "{e} epics · {s} stories",
    "story.hint": "Issues: {n}, from other epics: {f}",
    "story.foreignBadge": "+{n} from other epics",
    "story.foreignHint": "Story issues from other epics or without an epic: counted in the story total, not in the epic or project totals",
    "story.missing": "Not loaded (no access or deleted): {list}",
    "story.fromEpic": "from epic {key}",
    "story.noEpic": "no epic",
    "story.ownSprint": "The story has no issues — a bar for the story’s own sprint ({sprint}), no estimate",
    "story.projectBtn": "Project…",
    "story.projectBtnHint": "Change the epic’s project: the plugin posts an (omg project) comment to the epic",
    "story.projectTitle": "Project of epic {key}",
    "story.pickProject": "Existing project",
    "story.orNewProject": "or a new one",
    "story.newProject": "New project name",
    "story.publish": "Save to Jira",
    "story.publishing": "Posting a comment to Jira…",
    "story.notifyWarn": "The plugin will post a comment to the epic — Jira will email the epic’s watchers.",
    "story.publishError": "Failed to change the project of epic {key}: {msg}",
    "story.noPermission": "The “Add comments” permission is required in the Jira project.",
    "story.projectSaved": "Epic {key} moved to: {name}",
    "story.rename": "Rename…",
    "story.renameTitle": "Rename project",
    "story.renameWarn": "The new label will be posted as a comment to each epic of the project — {n} in total; watchers of each epic will get an email.",
    "story.renameScope": "Epics of this project that are not in your selection (chosen by other managers) are invisible to the plugin and keep the old name.",
    "story.renaming": "Posting: {i} of {n}…",
    "story.renamed": "Project renamed: “{name}”, epics: {n}",
    "story.renamePartial": "Renamed {ok} of {n} epics; failed (no permission to comment?): {list}",
    "tab.team": "Team",
    "gantt.personClick": "Expand every epic with {name}, collapse the rest",
    "gantt.epicClick": "Expand everyone with issues of {name}, collapse the rest",
    "gantt.epicFilter": "Expanded people with issues of: {name}",
    "gantt.personFilter": "Expanded epics with: {name}",
    "gantt.clearPersonFilter": "clear filter",
    "order.handle": "Drag to reorder epics. Without a mouse — Alt+↑ / Alt+↓",
    "order.handleAria": "Move epic {name}: Alt+↑ / Alt+↓",
    "order.manual": "Order: manual",
    "order.reset": "Reset order",
    "tab.settings": "Settings",

    "team.hint": "People from the download (assignees of target and other epics). Properties are stored locally and re-matched by name on every download.",
    "team.name": "Person",
    "team.team": "Team",
    "team.noTeams": "The team list is empty — set it in “Settings”",
    "team.board": "Team (board)",
    "team.issues": "Issues",
    "team.role": "Role",
    "team.systems": "Information systems",
    "team.status": "Status",
    "team.none": "—",
    "team.notLoaded": "not in download",
    "team.forget": "Delete profile",
    "team.noSystems": "The systems list is empty — set it in “Settings”",
    "team.empty": "No people yet: download epics first.",
    "team.saved": "Saved",
    "team.summaryTotal": "Employees: {n}",
    "team.summaryHint": "People from the download, excluding left and outstaff",
    "team.noRole": "no role",
    "role.developer": "Developer",
    "role.frontend": "Frontend dev",
    "role.backend": "Backend dev",
    "role.onec": "1C dev",
    "role.qa": "QA",
    "role.analytic": "Analytic",
    "role.teamlead": "Team Lead",
    "role.support": "Support",
    "role.pm": "Project Manager",
    "role.devops": "DevOps",
    "role.sysadm": "Sysadm",
    "pstatus.staff": "Staff",
    "pstatus.outstaff": "Outstaff",
    "pstatus.fired": "Left",
    "set.infoSystems": "Information systems",
    "set.infoSystemsHint": "One per line (or comma-separated). Used on the “Team” tab.",
    "set.teams": "Teams",
    "set.teamsHint": "One per line (or comma-separated). The “Team” tab picks a person’s team from this list; people are grouped by it on the “By people” tab when the Tempo API is unavailable.",

    "search.placeholder": "Epic summary or keys: PRJ-123, PRJ-124 — a list works too",
    "search.missing": "Epics not found: {list}. Check the keys — they may not be epics, or the project may be out of reach.",
    "search.find": "Search",
    "search.save": "Save selection",
    "search.results": "Found epics",
    "search.selected": "Epics selected: {n}",
    "search.empty": "Nothing found",
    "search.hint": "Tick the epics and press “Save selection” — their issues will be downloaded into the local database.",
    "search.selectAll": "Select all",
    "search.clear": "Clear selection",
    "search.stored": "Saved epics",
    "search.total": "Total: {n}",
    "search.created": "created",
    "search.plannedStart": "planned start",
    "search.plannedEnd": "planned end",
    "search.due": "due",
    "search.createdFull": "Epic creation date",
    "search.plannedStartFull": "Planned start of work",
    "search.plannedEndFull": "Planned end of work",
    "search.dueFull": "Due date",
    "search.col.key": "Key",
    "search.col.name": "Summary",
    "search.col.status": "Status",
    "search.col.project": "Project",
    "search.col.people": "Assignee / Reporter",
    "search.col.labels": "Labels",
    "search.col.express": "Express estimate",
    "search.expressFull": "Estimate entered on the epic itself: {sum}",
    "search.col.estimate": "Estimate",
    "search.estimateFull": "Total estimate of the epic’s issues: {sum} ({n} issues; cancelled excluded)",
    "search.col.spent": "Logged",
    "search.col.pct": "Done",
    "search.pctFull": "Done by estimates: {done} of {total} ({n} of {m} issues done)",
    "search.pctNone": "Issues have no estimates — share by count",
    "search.info": "Full epic details",
    "search.byProject": "Issues by Jira project",
    "fc.loading": "Computing the forecast…",
    "fc.outlook": "Chance to meet the due date: {chance}% · buffer {buffer} weeks",
    "fc.title": "Delivery forecast",
    "fc.none": "No forecast: the epic has no open issues or teams have no flow history",
    "fc.short": "No forecast: {n} full weeks of history, at least {min} required",
    "fc.warn": "{n} full weeks of history — the forecast is indicative (12+ is reliable, {ok})",
    "fc.line": "{pct}% — {weeks} weeks, by {date}",
    "fc.remaining": "Issues left: {n}",
    "fc.last": "Most often last: {team} ({pct}% of runs)",
    "fc.caveat": "Issues are assumed to be like historical ones; dependencies between them are ignored.",
    "flow.chart": "Completed issues by week",
    "flow.pickHint": "Pick one or several teams — the histogram, span and forecast are recomputed for them only.",
    "fc.basis": "Teams used: {teams}. Only they share the remaining issues. Flow history — {from} — {to}, {n} weeks: their working span on the epic, at least {ok} weeks.",
    "flow.all": "All teams",
    "flow.barHint": "{from} – {to}: completed {total}, of them in the epic {epic}",
    "flow.title": "Team flow and epic share",
    "flow.none": "Flow history is empty — press “Refresh”",
    "flow.short": "Full weeks: {n}. The forecast needs at least 5, 12+ is reliable.",
    "flow.window": "Window: {from} — {to}, full weeks: {n}",
    "flow.rowHint": "{team}: flow {median} issues/week (peak {max}). Epic share over its active span — {pct}% ({done} of {total} completed in {weeks} weeks); last {rw} weeks — {rpct}%; over the whole history window — {apct}% ({adone} of {atotal})",
    "people.estHint": "Section times use the remaining estimate; when it is empty, the original estimate is taken.",
    "flow.spanNote": "Share is measured over the epic’s active span: {from} — {to}, {n} weeks ({pct}% in total). Weeks outside the span are dimmed in the chart.",
    "flow.col": "team · flow · epic share",
    "share.title": "Logged hours by team",
    "share.loading": "Summing worklogs of the epic’s issues…",
    "share.none": "No worklogs since the epic was created",
    "share.error": "Could not compute: {msg}",
    "share.noTeam": "Outside teams",
    "share.header": "team · logged · capacity · share",
    "share.formula": "Capacity = members × {days} d × {hours} h × {sprints} sprints (since {from})",
    "share.rowHint": "{team}: logged {spent} of capacity {cap} ({members} people) — {pct}%",
    "search.infoTitle": "Epic {key}",
    "search.spentFull": "Time logged: on the epic {epic}, on its issues {issues} (issues with worklogs: {n} of {total})",
    "search.clearFilters": "Clear filters",
    "search.filters": "Filters:",
    "search.filterByLabel": "Show only epics with label “{v}”",
    "search.filterByAssignee": "Show only epics assigned to “{v}”",
    "search.filterLabel": "label",
    "search.filterAssignee": "assignee",
    "search.moreLabels": "{n} more",
    "search.assignee": "Assignee",
    "search.reporter": "Reporter",
    "gantt.filterAssignee": "Epic assignee",
    "gantt.filterAll": "— all —",
    "gantt.filterNone": "Unassigned",
    "gantt.fromSearch": "From the “Epic search” page:",
    "gantt.hiddenUnchecked": "hidden by unchecked boxes: {n}",
    "gantt.clearSearchFilters": "clear filters",
    "set.plannedStart": "“Planned start” field",
    "set.plannedEnd": "“Planned end” field",
    "set.plannedHint": "Date-type fields appear after “Detect Jira fields”. If auto-detection picked the wrong field (Jira may have several with the same name), choose the right one and press “Refresh data”.",
    "set.fieldAuto": "— not set —",
    "set.epicAssignee": "“Epic assignee” field",
    "set.epicReporter": "“Epic reporter” field",
    "set.peopleHint": "Defaults to the standard Assignee and Reporter. User-type fields appear after “Detect Jira fields”; press “Refresh data” after changing.",
    "set.stdAssignee": "Assignee (standard)",
    "set.stdReporter": "Reporter (standard)",
    "set.stdCreator": "Creator (standard)",

    "toolbar.refresh": "Refresh",
    "toolbar.reload": "Download",
    "toolbar.lastSync": "Updated: {t}",
    "toolbar.never": "never loaded",
    "toolbar.stats": "Epics: {e} · issues: {i} · sprints: {s}",

    "gantt.epic": "Epic",
    "gantt.assignee": "Assignee",
    "gantt.project": "Project",
    "gantt.count": "Issues",
    "gantt.sum": "Estimate",
    "gantt.noData": "No data. Pick epics on the “Epic search” tab.",
    "gantt.noSprints": "No active or future sprint found.",
    "gantt.noAssignee": "Unassigned",
    "gantt.noEpic": "No epic",
    "gantt.targetEpic": "Epic is selected on the “Search” tab",
    "gantt.current": "current",
    "gantt.future": "future",
    "gantt.team": "Team",
    "gantt.noTeam": "No team",
    "gantt.teamFromSprints": "Board #{id} is not accessible — the name is derived from its sprint names",
    "gantt.noDates": "No dates",
    "gantt.teams": "Boards:",
    "gantt.left": "Issues left not in “Done”",
    "gantt.others": "Other",
    "gantt.backlog": "Backlog",
    "gantt.offSprint": "Off sprint",
    "gantt.offSprintHint": "The issue is not in a sprint (kanban). Shown in the current section because it is in progress",
    "gantt.backlogHint": "no sprint, not done",
    "gantt.clickIssues": "Show issues",
    "gantt.doneShare": "Done: {done} of {total}",
    "gantt.overload": "Overloaded: {sum} vs sprint capacity {cap}",
    "gantt.headerMore": "{n} more — show all",
    "gantt.dueIn": "Due {date} · in {n} days",
    "gantt.dueToday": "Due {date} · today",
    "gantt.dueOverdue": "Due {date} · overdue by {n} days",
    "gantt.dueDone": "Due {date} · epic is done",
    "gantt.plannedIn": "Planned end {date} · in {n} days",
    "gantt.plannedToday": "Planned end {date} · today",
    "gantt.plannedOverdue": "Planned end {date} · passed {n} days ago",
    "gantt.plannedDone": "Planned end {date} · epic is done",
    "gantt.alsoPlanned": "planned end {date}",
    "gantt.dueBeforeChart": "before the current sprint",
    "gantt.dueAfterChart": "after the last sprint on the chart",
    "gantt.legendDue": "due ◆, planned ◇",
    "gantt.headerLess": "collapse the sprint list",
    "gantt.legendDone": "share of done issues",
    "tip.issuesCount": "Issues: {n}",
    "gantt.othersHint": "Issues in other epics (current and future sprints)",
    "gantt.targetPart": "Target epics",
    "gantt.otherPart": "Other epics",
    "tip.others": "Issues in other epics",
    "tip.systems": "Information systems",
    "crit.button": "Critical path: highlight people who define the epic end",
    "crit.on": "Critical path is on — remove highlight",
    "crit.defines": "defines the epic end: {rem} left, last sprint {sprint}",
    "crit.definesNoSprint": "defines the epic end: the largest remainder {rem}",
    "crit.overCapacity": "does not fit the due date: {rem} left vs {cap} capacity until {due}",
    "crit.none": "No critical people: no open estimated issues left",
    "cmt.button": "Comment",
    "cmt.title": "Comments · {key}",
    "cmt.placeholder": "New comment…",
    "cmt.save": "Save",
    "cmt.saving": "Saving…",
    "cmt.saved": "Saved",
    "cmt.loading": "Loading…",
    "cmt.empty": "No comments yet",
    "cmt.recent": "Latest {n}",
    "cmt.error": "Failed: {msg}",
    "cmt.mentionHint": "@ — mention a colleague (Jira will notify them)",
    "cmt.mentionSearching": "Searching…",
    "cmt.mentionNone": "Nobody found",
    "cmp.button": "Who can stand in",
    "cmp.title": "Stand-ins for {name}",
    "cmp.noProfile": "The person has no role or information systems set — fill them in on the “Team” tab.",
    "cmp.criteria": "Criteria: the same role and at least one shared information system; people who left are excluded.",
    "cmp.candidates": "Can stand in",
    "cmp.none": "No suitable people found.",
    "cmp.common": "shared systems: {n}",
    "cmp.load": "Sprint load",
    "cmp.loadCurrent": "current",
    "cmp.loadHint": "{caption}: {sum} of {cap} — {pct}%",
    "cmp.loadNoCap": "{caption}: {sum} (sprint capacity is not set)",
    "cmp.uncovered": "Systems with no stand-in",
    "cmp.allCovered": "all of the person’s systems are covered",
    "tip.noSystems": "not set",
    "tip.otherEpics": "Other epics (current and future sprints)",
    "st.othersLoading": "Loading people’s issues outside target epics: {n}",
    "err.others": "Failed to load people’s issues outside target epics: {msg}",
    "st.commentsLoading": "Reading epic and story comments: {n} of {total}",
    "st.linkedLoading": "Loading story issues from other epics: {n} of {total}",
    "err.comments": "Failed to read epic and story comments (project labels and notes kept as they were): {msg}",
    "err.linked": "Failed to load story issues from other epics: {msg}",
    "prio.none": "No priority",
    "set.storyTypes": "Story types",
    "set.storyTypesHint": "Comma-separated. Issues of these types in the selected epics are stories for the “Epic — story” view. They are never counted, even if missing from “Issue types left out of counts”. Use the name as Jira shows it in your language. Default — User Story, Story, История.",
    "set.storyLinkType": "Issue-to-story link",
    "set.storyLinkTypeHint": "Name of the Jira link type that ties issues to a story; direction does not matter. Default — Relates (“relates to”). Takes effect after “Refresh”.",
    "set.noteStaleDays": "Note is stale after, days",
    "set.noteStaleDaysHint": "An epic or story note older than this is marked as stale. Default — 14.",
    "gantt.expandAll": "Expand all",
    "gantt.collapseAll": "Collapse all",

    "tip.total": "Issues total",
    "tip.done": "Of them in “Done”",
    "tip.other": "Of them in other statuses",
    "tip.noSprint": "Issues without a sprint",
    "tip.sum": "Total estimate",
    "tip.byProject": "By project",
    "tip.byAssignee": "By assignee",
    "tip.close": "Close",

    "set.connection": "Connection",
    "set.baseUrl": "Jira URL",
    "set.baseUrlHint": "For example: https://jira.company.local",
    "set.pat": "Personal Access Token (fallback)",
    "set.patHint": "Used only when session cookies fail (401/403).",
    "set.grant": "Grant access to the domain",
    "set.test": "Test connection",
    "set.fields": "Fields",
    "set.estimateField": "What counts as estimate",
    "set.estimate.original": "Original Estimate (hours)",
    "set.estimate.remaining": "Remaining Estimate (hours)",
    "set.estimate.points": "Story Points",
    "set.hoursPerDay": "Hours per working day",
    "set.flowWeeks": "Flow history window (weeks)",
    "set.flowWeeksHint": "Completed issues are downloaded for this period — the basis of the delivery forecast. The forecast needs at least 5 full weeks, 12+ is reliable.",
    "set.flowDiag": "Flow history",
    "set.flowDiagEmpty": "Not downloaded yet — press “Refresh”.",
    "set.flowDiagText": "Issues with a resolution date: {n}, weeks with data: {weeks}, people: {people}.",
    "set.flowDiagGap": "Warning: {n} of {total} done issues in target epics have no resolution date ({pct}%) — their flow is invisible. Typically statuses outside the Done category, e.g. “On Prod”.",
    "set.flowDiagOk": "All done issues in target epics have a resolution date.",
    "set.tempo": "Take teams from Tempo",
    "set.tempoHint": "If Tempo is installed in Jira, team membership comes from it (/rest/tempo-teams/2/team). Otherwise the team is derived from the person’s sprint board.",
    "set.sprintDays": "Sprint length (working days)",
    "set.sprintDaysHint": "A person’s capacity per sprint: days × hours per day. When the estimates in a sprint exceed it, the cell on the “By people” tab is outlined in red.",
    "set.forecastExcludeTypes": "Issue types left out of counts",
    "set.forecastExcludeTypesHint": "Comma-separated. Such issues are not counted as epic issues (the “Saved epics” list and the “+” card: by project, progress, estimates, issues with worklogs) nor in the delivery forecast (team flow, epic share, histogram, remaining), the “By epics” bars and tooltips, or people load (the ⇄ window, overload in “Summary”). “By people” still shows all of a person’s issues. Time logged on them stays in “Logged”. Default — User Story: a story only groups issues that are counted anyway. For the forecast it takes effect after “Refresh”. “Story types” are always left out, even if not listed here.",
    "set.doneStatuses": "Statuses that mean “Done”",
    "set.doneStatusesHint": "Comma-separated statuses of your workflow counted as finished on top of the built-in ones (Done, Closed, On Prod). For example: Sign off, In support.",
    "set.detect": "Detect Jira fields",
    "set.detected": "Epic Link: {e} · Epic Name: {en} · Sprint: {s} · Story Points: {p} · Planned start: {ps} · Planned end: {pe}",
    "set.sprints": "Sprints",
    "set.board": "Board (rapid board)",
    "set.boardHint": "Sprints and their dates come from the board; with no board selected they are taken from the issues.",
    "set.boardNone": "— none (take from issues) —",
    "set.loadBoards": "Load boards",
    "set.save": "Save settings",
    "set.saved": "Settings saved",
    "set.config": "Preset configuration",
    "set.configHint": "JSON with the Jira URL, fields, the systems list, epic keys and people. The local database is wiped completely first (people profiles included), then applied step by step: fields and systems → epic download → people’s roles and systems. Download the current configuration with “Export”.",
    "set.configApply": "Load and apply",
    "set.configExport": "Export configuration",
    "set.configLog": "Log",
    "cfg.badJson": "Invalid JSON: {msg}",
    "cfg.baseUrlSet": "Jira URL: {url}",
    "cfg.fieldNotFound": "Field “{name}” not found in Jira",
    "cfg.fieldSet": "Field {key}: {id}",
    "cfg.systemsSet": "Information systems: {n}",
    "cfg.teamsSet": "Teams: {n}",
    "cfg.wiped": "Old database wiped (epics, issues, sprints, people profiles)",
    "cfg.epicsSaved": "Epics: {n} found and saved",
    "cfg.orderSet": "Manual epic order: {n}",
    "cfg.epicsMissing": "Epics not found: {list}",
    "cfg.peopleSaved": "People: {n} profiles updated",
    "cfg.badRole": "{name}: unknown role “{role}” — skipped",
    "cfg.badStatus": "{name}: unknown status “{status}” — skipped",
    "cfg.error": "Error: {msg}",
    "cfg.start": "Applying configuration…",
    "cfg.syncing": "Downloading epic issues…",
    "cfg.done": "Configuration applied",
    "set.danger": "Local database",
    "set.wipe": "Wipe database",
    "set.wipeDone": "Database wiped",

    "unit.h": "h",
    "unit.d": "d",
    "unit.sp": "SP",
    "dash": "—",

    "st.connecting": "Connecting…",
    "st.ok": "Connected: {name}",
    "st.epicsLoading": "Searching epics…",
    "st.issuesLoading": "Loading issues: {n}",
    "st.sprintsLoading": "Loading sprints…",
    "st.forecasting": "Computing epic forecasts…",
    "st.backfill": "Restoring epic history: {i} of {n}…",
    "st.saving": "Saving data…",
    "st.done": "Done",
    "st.schemaUpgrade": "Issues gained new fields — downloading everything again…",
    "st.flowLoading": "Loading completed-issue history: {n}",
    "st.flowSummary": "Flow history: {issues} completed issues over {weeks} weeks for {logins} people",
    "st.apiCheck": "Checking API availability…",
    "st.apiAgileLimited": "Jira Agile API is unavailable ({msg}) — boards and future sprint dates will not be loaded",
    "st.apiTempoLimited": "Jira Tempo API is unavailable ({msg}) — teams are taken from the “Team” tab",
    "st.tempoLoading": "Loading Tempo teams…",
    "st.tempoSummary": " · Tempo teams: {teams}, members: {members}",
    "st.sprintsSummary": "Done · open sprints: {n}, with dates: {dated}, without dates: {undated}{named}{failed}",
    "st.sprintsFromName": " · dates parsed from names: {n}",
    "st.sprintsFailed": " · could not re-read: {n}",
    "st.boardsFailed": "The configured board is unavailable — {list}. Sprints were re-read one by one.",
    "err.noBaseUrl": "Set the Jira URL in the settings",
    "err.auth": "Jira rejected the request. Log into Jira in this browser or set a PAT in the settings.",
    "err.apiCore": "The Jira API is unavailable: {msg}. Download is not possible.",
    "err.apiSearch": "JQL search is unavailable (/rest/api/2/search): {msg}. Download is not possible.",
    "err.http": "Jira error {code}: {msg}",
    "err.network": "Jira is unreachable — check the VPN and the network. If the VPN is on, check the Jira URL and the host permission. Data was not changed.",
    "err.noPermission": "No permission for the Jira domain. Press “Grant access to the domain” in the settings.",
    "err.noEpicField": "The “Epic Link” field was not found. Press “Detect Jira fields” in the settings."
  }
};
