// Словарь подписей интерфейса. Все тексты — только отсюда.
export const DICT = {
  ru: {
    "app.title": "Jira OhMyGant",
    "lang.label": "Язык",
    "app.today": "Сегодня",
    "about.version": "Версия",
    "about.author": "Автор",
    "search.dueSoon": "Срок через {n} дн.",
    "search.dueToday": "Срок сегодня",
    "search.overdue": "Срок прошёл {n} дн. назад",

    "tab.search": "Поиск",
    "tab.people": "По людям",
    "tab.epicPeople": "По эпикам",
    "tab.team": "Команда",
    "gantt.personClick": "Раскрыть все эпики с участием {name}, остальные свернуть",
    "gantt.personFilter": "Раскрыты эпики с участием: {name}",
    "gantt.clearPersonFilter": "снять фильтр",
    "tab.settings": "Настройки",

    "team.hint": "Люди из выгрузки (исполнители задач целевых и прочих эпиков). Свойства сохраняются локально и при повторной выгрузке сопоставляются по имени.",
    "team.name": "Сотрудник",
    "team.board": "Команда (доска)",
    "team.issues": "Задач",
    "team.role": "Роль",
    "team.systems": "Информационные системы",
    "team.status": "Статус",
    "team.none": "—",
    "team.notLoaded": "нет в выгрузке",
    "team.forget": "Удалить профиль",
    "team.noSystems": "Справочник систем пуст — задайте его в «Настройках»",
    "team.empty": "Нет людей: сначала выгрузите эпики.",
    "team.saved": "Сохранено",
    "team.summaryTotal": "Сотрудников: {n}",
    "team.summaryHint": "Люди из выгрузки без уволенных и аутстафа",
    "team.noRole": "без роли",
    "role.developer": "Developer",
    "role.frontend": "Frontend dev",
    "role.backend": "Backend dev",
    "role.onec": "1C dev",
    "role.qa": "QA",
    "role.analytic": "Analytic",
    "role.teamlead": "Team Lead",
    "role.support": "Support",
    "role.pm": "Project Manager",
    "role.devops": "DevOps",
    "role.sysadm": "Sysadm",
    "pstatus.staff": "Штатный сотрудник",
    "pstatus.outstaff": "Аутстаф",
    "pstatus.fired": "Уволен",
    "set.infoSystems": "Информационные системы",
    "set.infoSystemsHint": "По одной в строке (или через запятую). Используются на вкладке «Команда».",

    "search.placeholder": "Название эпика или ключ (PRJ-123)",
    "search.find": "Найти",
    "search.save": "Сохранить выбор",
    "search.results": "Найденные эпики",
    "search.selected": "Выбрано эпиков: {n}",
    "search.empty": "Ничего не найдено",
    "search.hint": "Отметьте эпики и нажмите «Сохранить выбор» — задачи будут скачаны в локальную базу.",
    "search.selectAll": "Выбрать все",
    "search.clear": "Снять выбор",
    "search.stored": "Сохранённые эпики",
    "search.total": "Всего: {n}",
    "search.created": "создан",
    "search.plannedStart": "план. начало",
    "search.plannedEnd": "план. завершение",
    "search.due": "срок",
    "search.createdFull": "Дата создания эпика",
    "search.plannedStartFull": "Плановое начало работ (Planned start)",
    "search.plannedEndFull": "Плановое завершение работ (Planned end)",
    "search.dueFull": "Срок исполнения (Due date)",
    "search.col.key": "Ключ",
    "search.col.name": "Название",
    "search.col.status": "Статус",
    "search.col.project": "Проект",
    "search.col.people": "Исполнитель / Постановщик",
    "search.col.labels": "Метки",
    "search.col.spent": "Списано",
    "search.col.pct": "Готово",
    "search.pctFull": "Выполнено по оценкам: {done} из {total} ({n} задач из {m} готово)",
    "search.pctNone": "У задач нет оценок — доля по количеству",
    "search.info": "Вся информация по эпику",
    "search.byProject": "Задач по проектам Jira",
    "search.infoTitle": "Эпик {key}",
    "search.spentFull": "Списано времени: на сам эпик {epic}, на его задачи {issues} (задач со списаниями: {n} из {total})",
    "search.clearFilters": "Снять фильтры",
    "search.filters": "Фильтры:",
    "search.filterByLabel": "Показать только эпики с меткой «{v}»",
    "search.filterByAssignee": "Показать только эпики исполнителя «{v}»",
    "search.filterLabel": "метка",
    "search.filterAssignee": "исполнитель",
    "search.moreLabels": "ещё {n}",
    "search.assignee": "Исполнитель",
    "search.reporter": "Постановщик",
    "gantt.filterAssignee": "Исполнитель эпика",
    "gantt.filterAll": "— все —",
    "gantt.filterNone": "Без исполнителя",
    "gantt.fromSearch": "Со страницы «Поиск эпиков»:",
    "gantt.hiddenUnchecked": "скрыто снятыми галочками: {n}",
    "gantt.clearSearchFilters": "снять фильтры",
    "set.plannedStart": "Поле «Плановое начало»",
    "set.plannedEnd": "Поле «Плановое завершение»",
    "set.plannedHint": "Список полей типа «дата» появляется после «Определить поля Jira». Если автоопределение выбрало не то поле (в Jira бывают одноимённые), укажите нужное вручную и нажмите «Обновить данные».",
    "set.fieldAuto": "— не задано —",
    "set.epicAssignee": "Поле «Исполнитель эпика»",
    "set.epicReporter": "Поле «Постановщик эпика»",
    "set.peopleHint": "По умолчанию — стандартные Assignee и Reporter. Список полей типа «пользователь» появляется после «Определить поля Jira»; после смены нажмите «Обновить данные».",
    "set.stdAssignee": "Assignee (стандартное)",
    "set.stdReporter": "Reporter (стандартное)",
    "set.stdCreator": "Creator (стандартное)",

    "toolbar.refresh": "Обновить",
    "toolbar.reload": "Скачать",
    "toolbar.lastSync": "Обновлено: {t}",
    "toolbar.never": "ещё не загружалось",
    "toolbar.stats": "Эпиков: {e} · задач: {i} · спринтов: {s}",

    "gantt.epic": "Эпик",
    "gantt.assignee": "Исполнитель",
    "gantt.project": "Проект",
    "gantt.count": "Задач",
    "gantt.sum": "Оценка",
    "gantt.noData": "Нет данных. Выберите эпики на вкладке «Поиск эпиков».",
    "gantt.noSprints": "Не найдено ни одного текущего или будущего спринта.",
    "gantt.noAssignee": "Без исполнителя",
    "gantt.current": "текущий",
    "gantt.future": "будущий",
    "gantt.team": "Команда",
    "gantt.noTeam": "Без команды",
    "gantt.noDates": "Без дат",
    "gantt.teams": "Команды:",
    "gantt.left": "Осталось задач не в статусе «Готово»",
    "gantt.others": "Прочие",
    "gantt.backlog": "Бэклог",
    "gantt.backlogHint": "без спринта, не готово",
    "gantt.clickIssues": "Показать задачи",
    "gantt.doneShare": "Готово: {done} из {total}",
    "gantt.headerMore": "ещё {n} — показать все",
    "gantt.dueIn": "Срок {date} · через {n} дн.",
    "gantt.dueToday": "Срок {date} · сегодня",
    "gantt.dueOverdue": "Срок {date} · просрочен на {n} дн.",
    "gantt.dueDone": "Срок {date} · эпик готов",
    "gantt.dueBeforeChart": "раньше текущего спринта",
    "gantt.dueAfterChart": "позже последнего спринта на графике",
    "gantt.legendDue": "срок исполнения",
    "gantt.headerLess": "свернуть список спринтов",
    "gantt.legendDone": "доля готовых задач",
    "tip.issuesCount": "Задач: {n}",
    "gantt.othersHint": "Задачи в прочих эпиках (текущий и будущие спринты)",
    "gantt.targetPart": "Целевые эпики",
    "gantt.otherPart": "Прочие эпики",
    "tip.others": "Задач в прочих эпиках",
    "tip.systems": "Информационные системы",
    "crit.button": "Критический путь: подсветить людей, определяющих срок эпика",
    "crit.on": "Критический путь включён — снять подсветку",
    "crit.defines": "определяет конец эпика: остаток {rem}, последний спринт {sprint}",
    "crit.definesNoSprint": "определяет конец эпика: самый большой остаток {rem}",
    "crit.overCapacity": "не укладывается в срок: остаток {rem} при ёмкости {cap} до {due}",
    "crit.none": "Критичных людей нет: открытых задач с оценкой не осталось",
    "cmt.button": "Прокомментировать",
    "cmt.title": "Комментарии · {key}",
    "cmt.placeholder": "Новый комментарий…",
    "cmt.save": "Сохранить",
    "cmt.saving": "Сохраняем…",
    "cmt.saved": "Сохранено",
    "cmt.loading": "Загрузка…",
    "cmt.empty": "Комментариев пока нет",
    "cmt.recent": "Последние {n}",
    "cmt.error": "Не удалось: {msg}",
    "cmt.mentionHint": "@ — упомянуть коллегу (Jira пришлёт ему уведомление)",
    "cmt.mentionSearching": "Ищем…",
    "cmt.mentionNone": "Никого не найдено",
    "cmp.button": "Кто может подменить",
    "cmp.title": "Замена для {name}",
    "cmp.noProfile": "У сотрудника не заполнены роль или информационные системы — задайте их на вкладке «Команда».",
    "cmp.criteria": "Критерии: та же роль и хотя бы одна общая информационная система; уволенные не учитываются.",
    "cmp.candidates": "Могут подменить",
    "cmp.none": "Подходящих сотрудников не найдено.",
    "cmp.common": "общих систем: {n}",
    "cmp.uncovered": "Системы без замены",
    "cmp.allCovered": "все системы сотрудника покрыты",
    "tip.noSystems": "не указаны",
    "tip.otherEpics": "Прочие эпики (текущий и будущие спринты)",
    "st.othersLoading": "Загружаем задачи людей вне целевых эпиков: {n}",
    "err.others": "Не удалось загрузить задачи людей вне целевых эпиков: {msg}",
    "gantt.expandAll": "Развернуть всё",
    "gantt.collapseAll": "Свернуть всё",

    "tip.total": "Всего задач",
    "tip.done": "Из них в статусе «Готово»",
    "tip.other": "Из них в прочих статусах",
    "tip.noSprint": "Задач без спринта",
    "tip.sum": "Суммарная оценка",
    "tip.byProject": "По проектам",
    "tip.byAssignee": "По исполнителям",
    "tip.close": "Закрыть",

    "set.connection": "Подключение",
    "set.baseUrl": "Адрес Jira",
    "set.baseUrlHint": "Например: https://jira.company.local",
    "set.pat": "Personal Access Token (запасной способ)",
    "set.patHint": "Используется, только если сессионные cookie не сработали (401/403).",
    "set.grant": "Разрешить доступ к домену",
    "set.test": "Проверить подключение",
    "set.fields": "Поля",
    "set.estimateField": "Что считать оценкой",
    "set.estimate.original": "Original Estimate (часы)",
    "set.estimate.remaining": "Remaining Estimate (часы)",
    "set.estimate.points": "Story Points",
    "set.hoursPerDay": "Часов в рабочем дне",
    "set.doneStatuses": "Статусы, означающие «Готово»",
    "set.doneStatusesHint": "Через запятую — статусы вашего потока, которые считаются завершёнными сверх стандартных (Готово, Закрыто, On Prod). Например: Sign off, На саппорте.",
    "set.detect": "Определить поля Jira",
    "set.detected": "Epic Link: {e} · Sprint: {s} · Story Points: {p} · Planned start: {ps} · Planned end: {pe}",
    "set.sprints": "Спринты",
    "set.board": "Доска (rapid board)",
    "set.boardHint": "Спринты и их даты берутся с доски; если доска не выбрана — из полей самих задач.",
    "set.boardNone": "— не выбрана (брать из задач) —",
    "set.loadBoards": "Загрузить список досок",
    "set.save": "Сохранить настройки",
    "set.saved": "Настройки сохранены",
    "set.config": "Предварительная конфигурация",
    "set.configHint": "JSON с адресом Jira, полями, справочником систем, списком эпиков и сотрудниками. Перед применением локальная база очищается полностью (включая профили сотрудников), затем по шагам: поля и системы → выгрузка эпиков → роли и системы сотрудников. Файл с текущей конфигурацией можно скачать кнопкой «Экспорт».",
    "set.configApply": "Загрузить и применить",
    "set.configExport": "Экспорт конфигурации",
    "set.configLog": "Журнал",
    "cfg.badJson": "Некорректный JSON: {msg}",
    "cfg.baseUrlSet": "Адрес Jira: {url}",
    "cfg.fieldNotFound": "Поле «{name}» не найдено в Jira",
    "cfg.fieldSet": "Поле {key}: {id}",
    "cfg.systemsSet": "Информационные системы: {n}",
    "cfg.wiped": "Старая база очищена (эпики, задачи, спринты, профили сотрудников)",
    "cfg.epicsSaved": "Эпики: найдено и сохранено {n}",
    "cfg.epicsMissing": "Не найдены эпики: {list}",
    "cfg.peopleSaved": "Сотрудники: обновлено профилей {n}",
    "cfg.badRole": "{name}: неизвестная роль «{role}» — пропущена",
    "cfg.badStatus": "{name}: неизвестный статус «{status}» — пропущен",
    "cfg.error": "Ошибка: {msg}",
    "cfg.start": "Применяем конфигурацию…",
    "cfg.syncing": "Выгружаем задачи эпиков…",
    "cfg.done": "Конфигурация применена",
    "set.danger": "Локальная база",
    "set.wipe": "Очистить базу",
    "set.wipeDone": "База очищена",

    "unit.h": "ч",
    "unit.d": "д",
    "unit.sp": "SP",
    "dash": "—",

    "st.connecting": "Подключение…",
    "st.ok": "Подключено: {name}",
    "st.epicsLoading": "Ищем эпики…",
    "st.issuesLoading": "Загружаем задачи: {n}",
    "st.sprintsLoading": "Загружаем спринты…",
    "st.done": "Готово",
    "st.schemaUpgrade": "В задачах появились новые поля — выгружаем всё заново…",
    "st.sprintsSummary": "Готово · незакрытых спринтов: {n}, с датами: {dated}, без дат: {undated}{named}{failed}",
    "st.sprintsFromName": " · даты из названия: {n}",
    "st.sprintsFailed": " · не удалось перечитать: {n}",
    "st.boardsFailed": "Доска из настроек недоступна — {list}. Спринты перечитаны по одному.",
    "err.noBaseUrl": "Укажите адрес Jira в настройках",
    "err.auth": "Jira не авторизовала запрос. Войдите в Jira в этом браузере или укажите PAT в настройках.",
    "err.http": "Ошибка Jira {code}: {msg}",
    "err.network": "Не удалось связаться с Jira. Проверьте адрес и выданное разрешение на домен.",
    "err.noPermission": "Нет разрешения на домен Jira. Нажмите «Разрешить доступ к домену» в настройках.",
    "err.noEpicField": "Не найдено поле «Epic Link». Нажмите «Определить поля Jira» в настройках."
  },

  en: {
    "app.title": "Jira OhMyGant",
    "lang.label": "Language",
    "app.today": "Today",
    "about.version": "Version",
    "about.author": "Author",
    "search.dueSoon": "Due in {n} days",
    "search.dueToday": "Due today",
    "search.overdue": "Overdue by {n} days",

    "tab.search": "Search",
    "tab.people": "By people",
    "tab.epicPeople": "By epics",
    "tab.team": "Team",
    "gantt.personClick": "Expand every epic with {name}, collapse the rest",
    "gantt.personFilter": "Expanded epics with: {name}",
    "gantt.clearPersonFilter": "clear filter",
    "tab.settings": "Settings",

    "team.hint": "People from the download (assignees of target and other epics). Properties are stored locally and re-matched by name on every download.",
    "team.name": "Person",
    "team.board": "Team (board)",
    "team.issues": "Issues",
    "team.role": "Role",
    "team.systems": "Information systems",
    "team.status": "Status",
    "team.none": "—",
    "team.notLoaded": "not in download",
    "team.forget": "Delete profile",
    "team.noSystems": "The systems list is empty — set it in “Settings”",
    "team.empty": "No people yet: download epics first.",
    "team.saved": "Saved",
    "team.summaryTotal": "Employees: {n}",
    "team.summaryHint": "People from the download, excluding left and outstaff",
    "team.noRole": "no role",
    "role.developer": "Developer",
    "role.frontend": "Frontend dev",
    "role.backend": "Backend dev",
    "role.onec": "1C dev",
    "role.qa": "QA",
    "role.analytic": "Analytic",
    "role.teamlead": "Team Lead",
    "role.support": "Support",
    "role.pm": "Project Manager",
    "role.devops": "DevOps",
    "role.sysadm": "Sysadm",
    "pstatus.staff": "Staff",
    "pstatus.outstaff": "Outstaff",
    "pstatus.fired": "Left",
    "set.infoSystems": "Information systems",
    "set.infoSystemsHint": "One per line (or comma-separated). Used on the “Team” tab.",

    "search.placeholder": "Epic summary or key (PRJ-123)",
    "search.find": "Search",
    "search.save": "Save selection",
    "search.results": "Found epics",
    "search.selected": "Epics selected: {n}",
    "search.empty": "Nothing found",
    "search.hint": "Tick the epics and press “Save selection” — their issues will be downloaded into the local database.",
    "search.selectAll": "Select all",
    "search.clear": "Clear selection",
    "search.stored": "Saved epics",
    "search.total": "Total: {n}",
    "search.created": "created",
    "search.plannedStart": "planned start",
    "search.plannedEnd": "planned end",
    "search.due": "due",
    "search.createdFull": "Epic creation date",
    "search.plannedStartFull": "Planned start of work",
    "search.plannedEndFull": "Planned end of work",
    "search.dueFull": "Due date",
    "search.col.key": "Key",
    "search.col.name": "Summary",
    "search.col.status": "Status",
    "search.col.project": "Project",
    "search.col.people": "Assignee / Reporter",
    "search.col.labels": "Labels",
    "search.col.spent": "Logged",
    "search.col.pct": "Done",
    "search.pctFull": "Done by estimates: {done} of {total} ({n} of {m} issues done)",
    "search.pctNone": "Issues have no estimates — share by count",
    "search.info": "Full epic details",
    "search.byProject": "Issues by Jira project",
    "search.infoTitle": "Epic {key}",
    "search.spentFull": "Time logged: on the epic {epic}, on its issues {issues} (issues with worklogs: {n} of {total})",
    "search.clearFilters": "Clear filters",
    "search.filters": "Filters:",
    "search.filterByLabel": "Show only epics with label “{v}”",
    "search.filterByAssignee": "Show only epics assigned to “{v}”",
    "search.filterLabel": "label",
    "search.filterAssignee": "assignee",
    "search.moreLabels": "{n} more",
    "search.assignee": "Assignee",
    "search.reporter": "Reporter",
    "gantt.filterAssignee": "Epic assignee",
    "gantt.filterAll": "— all —",
    "gantt.filterNone": "Unassigned",
    "gantt.fromSearch": "From the “Epic search” page:",
    "gantt.hiddenUnchecked": "hidden by unchecked boxes: {n}",
    "gantt.clearSearchFilters": "clear filters",
    "set.plannedStart": "“Planned start” field",
    "set.plannedEnd": "“Planned end” field",
    "set.plannedHint": "Date-type fields appear after “Detect Jira fields”. If auto-detection picked the wrong field (Jira may have several with the same name), choose the right one and press “Refresh data”.",
    "set.fieldAuto": "— not set —",
    "set.epicAssignee": "“Epic assignee” field",
    "set.epicReporter": "“Epic reporter” field",
    "set.peopleHint": "Defaults to the standard Assignee and Reporter. User-type fields appear after “Detect Jira fields”; press “Refresh data” after changing.",
    "set.stdAssignee": "Assignee (standard)",
    "set.stdReporter": "Reporter (standard)",
    "set.stdCreator": "Creator (standard)",

    "toolbar.refresh": "Refresh",
    "toolbar.reload": "Download",
    "toolbar.lastSync": "Updated: {t}",
    "toolbar.never": "never loaded",
    "toolbar.stats": "Epics: {e} · issues: {i} · sprints: {s}",

    "gantt.epic": "Epic",
    "gantt.assignee": "Assignee",
    "gantt.project": "Project",
    "gantt.count": "Issues",
    "gantt.sum": "Estimate",
    "gantt.noData": "No data. Pick epics on the “Epic search” tab.",
    "gantt.noSprints": "No active or future sprint found.",
    "gantt.noAssignee": "Unassigned",
    "gantt.current": "current",
    "gantt.future": "future",
    "gantt.team": "Team",
    "gantt.noTeam": "No team",
    "gantt.noDates": "No dates",
    "gantt.teams": "Teams:",
    "gantt.left": "Issues left not in “Done”",
    "gantt.others": "Other",
    "gantt.backlog": "Backlog",
    "gantt.backlogHint": "no sprint, not done",
    "gantt.clickIssues": "Show issues",
    "gantt.doneShare": "Done: {done} of {total}",
    "gantt.headerMore": "{n} more — show all",
    "gantt.dueIn": "Due {date} · in {n} days",
    "gantt.dueToday": "Due {date} · today",
    "gantt.dueOverdue": "Due {date} · overdue by {n} days",
    "gantt.dueDone": "Due {date} · epic is done",
    "gantt.dueBeforeChart": "before the current sprint",
    "gantt.dueAfterChart": "after the last sprint on the chart",
    "gantt.legendDue": "due date",
    "gantt.headerLess": "collapse the sprint list",
    "gantt.legendDone": "share of done issues",
    "tip.issuesCount": "Issues: {n}",
    "gantt.othersHint": "Issues in other epics (current and future sprints)",
    "gantt.targetPart": "Target epics",
    "gantt.otherPart": "Other epics",
    "tip.others": "Issues in other epics",
    "tip.systems": "Information systems",
    "crit.button": "Critical path: highlight people who define the epic end",
    "crit.on": "Critical path is on — remove highlight",
    "crit.defines": "defines the epic end: {rem} left, last sprint {sprint}",
    "crit.definesNoSprint": "defines the epic end: the largest remainder {rem}",
    "crit.overCapacity": "does not fit the due date: {rem} left vs {cap} capacity until {due}",
    "crit.none": "No critical people: no open estimated issues left",
    "cmt.button": "Comment",
    "cmt.title": "Comments · {key}",
    "cmt.placeholder": "New comment…",
    "cmt.save": "Save",
    "cmt.saving": "Saving…",
    "cmt.saved": "Saved",
    "cmt.loading": "Loading…",
    "cmt.empty": "No comments yet",
    "cmt.recent": "Latest {n}",
    "cmt.error": "Failed: {msg}",
    "cmt.mentionHint": "@ — mention a colleague (Jira will notify them)",
    "cmt.mentionSearching": "Searching…",
    "cmt.mentionNone": "Nobody found",
    "cmp.button": "Who can stand in",
    "cmp.title": "Stand-ins for {name}",
    "cmp.noProfile": "The person has no role or information systems set — fill them in on the “Team” tab.",
    "cmp.criteria": "Criteria: the same role and at least one shared information system; people who left are excluded.",
    "cmp.candidates": "Can stand in",
    "cmp.none": "No suitable people found.",
    "cmp.common": "shared systems: {n}",
    "cmp.uncovered": "Systems with no stand-in",
    "cmp.allCovered": "all of the person’s systems are covered",
    "tip.noSystems": "not set",
    "tip.otherEpics": "Other epics (current and future sprints)",
    "st.othersLoading": "Loading people’s issues outside target epics: {n}",
    "err.others": "Failed to load people’s issues outside target epics: {msg}",
    "gantt.expandAll": "Expand all",
    "gantt.collapseAll": "Collapse all",

    "tip.total": "Issues total",
    "tip.done": "Of them in “Done”",
    "tip.other": "Of them in other statuses",
    "tip.noSprint": "Issues without a sprint",
    "tip.sum": "Total estimate",
    "tip.byProject": "By project",
    "tip.byAssignee": "By assignee",
    "tip.close": "Close",

    "set.connection": "Connection",
    "set.baseUrl": "Jira URL",
    "set.baseUrlHint": "For example: https://jira.company.local",
    "set.pat": "Personal Access Token (fallback)",
    "set.patHint": "Used only when session cookies fail (401/403).",
    "set.grant": "Grant access to the domain",
    "set.test": "Test connection",
    "set.fields": "Fields",
    "set.estimateField": "What counts as estimate",
    "set.estimate.original": "Original Estimate (hours)",
    "set.estimate.remaining": "Remaining Estimate (hours)",
    "set.estimate.points": "Story Points",
    "set.hoursPerDay": "Hours per working day",
    "set.doneStatuses": "Statuses that mean “Done”",
    "set.doneStatusesHint": "Comma-separated statuses of your workflow counted as finished on top of the built-in ones (Done, Closed, On Prod). For example: Sign off, In support.",
    "set.detect": "Detect Jira fields",
    "set.detected": "Epic Link: {e} · Sprint: {s} · Story Points: {p} · Planned start: {ps} · Planned end: {pe}",
    "set.sprints": "Sprints",
    "set.board": "Board (rapid board)",
    "set.boardHint": "Sprints and their dates come from the board; with no board selected they are taken from the issues.",
    "set.boardNone": "— none (take from issues) —",
    "set.loadBoards": "Load boards",
    "set.save": "Save settings",
    "set.saved": "Settings saved",
    "set.config": "Preset configuration",
    "set.configHint": "JSON with the Jira URL, fields, the systems list, epic keys and people. The local database is wiped completely first (people profiles included), then applied step by step: fields and systems → epic download → people’s roles and systems. Download the current configuration with “Export”.",
    "set.configApply": "Load and apply",
    "set.configExport": "Export configuration",
    "set.configLog": "Log",
    "cfg.badJson": "Invalid JSON: {msg}",
    "cfg.baseUrlSet": "Jira URL: {url}",
    "cfg.fieldNotFound": "Field “{name}” not found in Jira",
    "cfg.fieldSet": "Field {key}: {id}",
    "cfg.systemsSet": "Information systems: {n}",
    "cfg.wiped": "Old database wiped (epics, issues, sprints, people profiles)",
    "cfg.epicsSaved": "Epics: {n} found and saved",
    "cfg.epicsMissing": "Epics not found: {list}",
    "cfg.peopleSaved": "People: {n} profiles updated",
    "cfg.badRole": "{name}: unknown role “{role}” — skipped",
    "cfg.badStatus": "{name}: unknown status “{status}” — skipped",
    "cfg.error": "Error: {msg}",
    "cfg.start": "Applying configuration…",
    "cfg.syncing": "Downloading epic issues…",
    "cfg.done": "Configuration applied",
    "set.danger": "Local database",
    "set.wipe": "Wipe database",
    "set.wipeDone": "Database wiped",

    "unit.h": "h",
    "unit.d": "d",
    "unit.sp": "SP",
    "dash": "—",

    "st.connecting": "Connecting…",
    "st.ok": "Connected: {name}",
    "st.epicsLoading": "Searching epics…",
    "st.issuesLoading": "Loading issues: {n}",
    "st.sprintsLoading": "Loading sprints…",
    "st.done": "Done",
    "st.schemaUpgrade": "Issues gained new fields — downloading everything again…",
    "st.sprintsSummary": "Done · open sprints: {n}, with dates: {dated}, without dates: {undated}{named}{failed}",
    "st.sprintsFromName": " · dates parsed from names: {n}",
    "st.sprintsFailed": " · could not re-read: {n}",
    "st.boardsFailed": "The configured board is unavailable — {list}. Sprints were re-read one by one.",
    "err.noBaseUrl": "Set the Jira URL in the settings",
    "err.auth": "Jira rejected the request. Log into Jira in this browser or set a PAT in the settings.",
    "err.http": "Jira error {code}: {msg}",
    "err.network": "Cannot reach Jira. Check the URL and the granted host permission.",
    "err.noPermission": "No permission for the Jira domain. Press “Grant access to the domain” in the settings.",
    "err.noEpicField": "The “Epic Link” field was not found. Press “Detect Jira fields” in the settings."
  }
};
